model_list:
 - model_name: gpt-4
   love_engine_params:
     model: openai/fake
     api_key: fake-key
     api_base: os.environ/FAKE_OPENAI_API_BASE
     tags: ["teamA"]
   model_info:
     id: "team-a-model"

love_engine_settings:
  cache: true
  callbacks: ["prometheus"]

router_settings:
  enable_tag_filtering: True # 👈 Key Change

